# Generated by Django 3.1.4 on 2021-02-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booked_by_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
