# Generated by Django 3.1.4 on 2021-02-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(default='./static/img/default.png', null=True, upload_to='static/img/'),
        ),
    ]
